### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by gwendalp** [zuzuba/CISR_NeurIPS20#2]
You said the learning is safe for the student.
When learning in an induced CMDP Mi, I understand that the student is safe w.r.t. Di, but what happened if 
student fall into D \ Di. If I correctly understood, there is no intervention in D \ Di when acting in Mi, therefore the student could crash ?  Thank you for your answer.

**Comment by zuzuba** [comment]
I will answer the question even though the issue is closed in case someone else stumbles upon the same question. 

The answer to this question is in proposition 2, which states the conditions under which learning in Mi is safe with respect to the original set of unsafe states D. In particular, if Di "surrounds" D and there is zero chance that the agent can "jump" from a state in S \ Di to a state in D, safety is guaranteed. 

This assumption may not hold in some real case scenarios (as we argue after assumption 2). In this sense, we say that "CISR informally keeps the student as safe during training as teacher’s interventions allow". However, for reasonably defined Di, the agent should attain safety in practice unless it actively tries to circumvent the teacher's intervention. 

A practical demonstration of this is the lunar lander experiment where sometimes the student crashes during training even though its state is within the velocity and tilt angle allowed by the teacher. Nonetheless, these cases are very rare as they happen around 2 times per training under CISR (which consists of 1.5e6 steps), in contrast with the 1.2e3 when training in the original environment.
